name: Check Web Service Status

on:
  schedule:
    - cron: '*/5 * * * *'  # Run the job every hour

jobs:
  check_service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      
        with:
          token: ${{ CACD }}
      - run: |
          # Replace <YOUR_URL> with the URL of the web service you want to check
          SERVICE_URL="https://spsrc31.iaa.csic.es/argus/availability"
          
          # Use curl to check if the service is up (200 OK response)
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $SERVICE_URL)
          
          if [ $STATUS_CODE -eq 200 ]; then
            STATUS_TEXT="Service is up!"
          else
            STATUS_TEXT="Service is down!"
          fi

          echo "$TIMESTAMP,argus,$STATUS_TEXT" >> service_status.csv
          
          TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add service_status.csv
          git commit -m "Update service status - $TIMESTAMP"
          git push


        if: always()
